### signs a user in
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
  "email": "some_email@gmail.com",
  "password": "!adm123@"
}

### logins a user
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
  "email": "some_email@gmail.com",
  "password": "!adm123@"
}